### ISSUE TITLE
Cannot create methods other than getters and setters in managed entities

### ISSUE THREAD

**Issue by mdamak** [doanduyhai/Achilles#192]
This is my entity 

```java
@Entity(table = "total_users")
public class TotalUsers {

	@PartitionKey
	@TypeTransformer(valueCodecClass = LocalDateToString.class)
	public LocalDate day;

	@Column
	public Counter morning;
	@Column
	public Counter noon;
	@Column
	public Counter afternoon;
	@Column
	public Counter accesspt;
	@Column
	public Counter night;
```
I added this method to get a counter from a timeslot

```java
	public Counter counterForTimeslot(Timeslot timeslot) {
		switch (timeslot) {
		case MORNING : return this.getMorning();
		case NOON : return this.getNoon();
		case AFTERNOON: return this.getAfternoon();
		case ACCESSPT : return this.getAccesspt();
		case NIGHT : return this.getNight();
		}
		return null;
	}
```
But this mehod return always a null Object.
When I move this method in my service, I get the value of the counter.

**Comment by doanduyhai** [comment]
Hello

 You are facing the classical problem of "self-invocation" inside a Proxy (see here: http://stackoverflow.com/questions/8039041/how-to-handle-internal-calls-on-spring-ejb-mockito-proxies)

 Indeed, **Achilles** returns a proxy object of  **`TotalUsers`** and all calls to getters are intercepted. However internal call like `this.getMorning()` will not be intercepted by the CGLib proxy, thus returning null.

 There is no solution other than moving your **`counterForTimeslot()`** method outside of the entity.

 In the next version of Achilles (4.0) I'll drop CGLib proxy to use compile-time generated subclasses to avoid this kind of limitation

**Comment by ElPicador** [comment]
Do you know when you expect to release the next version ?
Is it weeks, months, years away ?

Thanks

**Comment by doanduyhai** [comment]
Draft estimate: March/April 2015

 This is a major redesign, we're going to remove completely CGLib proxies to replace them by compile-time sub-classes using Annotation Processing Tool so it may take some time to be released
