### ISSUE TITLE
unable to create indexes using CASE_SENSITIVE naming convention

### ISSUE THREAD

**Issue by vladimirdolzhenko** [doanduyhai/Achilles#196]
Using NamingStrategy.CASE_SENSITIVE as ConfigurationParameters.GLOBAL_NAMING_STRATEGY

and entity has column like

```java
@Column
private String myName
```

in that case cqlColumnName is **"myName"** (surrounded with double quotes) and 
PropertyMetaTableCreator.createNewIndexScript makes the index name like
**myEntity_"myName"_idx** 

that's finally fails as incorrect index name

**Comment by doanduyhai** [comment]
Ha, good catch ! Need to fix that!

**Comment by vladimirdolzhenko** [comment]
Moreover - **EntityMapper.mapRowToEntityWithPrimaryKey** gets columnDefinitions in lower case - seems global naming strategy doesn't matter for that -> therefore not all fields are populated

**Comment by doanduyhai** [comment]
Sure, it's a bug

**Comment by vladimirdolzhenko** [comment]
Strange - columnDefinitions in lower case came from datastax cassandra driver - could it be some wrong configuration of embedded cassandra ?

**Comment by doanduyhai** [comment]
Oh I remember that now. There were some mismatch from the Driver.

**Comment by vladimirdolzhenko** [comment]
I would be nice to have fast-fail check: e.g. on making (indexed) query - in case of lowercase it worth to throw an exception on query construction neither got an error from cassandra driver that there is no such index. as well for case sensitive - at least debug message in EntityMapper.mapRowToEntityWithPrimaryKey  that pm isn't mapped to any property - could be issue.

**Comment by vladimirdolzhenko** [comment]
Another issue:
let's use default (lower case) naming strategy:

**EntityMapper.mapRowToEntityWithPrimaryKey** tries to get **PropertyMeta** from **propertiesMap** using **columnName** that is completely **WRONG**

**Comment by vladimirdolzhenko** [comment]
As well for IndexedConditions - naming convention (and transformation) is the internal routine of Achilles - it has to transform to properly cql name internally e.g.

```java
public static final String COLUMN_NAME = "simpleName";
@Column(name = COLUMN_NAME)
private String name;
```

so - Achilles translates into simplename (by default) as well if we create IndexedCondition(COLUMN_NAME) it has to be transformed properly internally.

@doanduyhai  Do you agree?

**Comment by doanduyhai** [comment]
"and the root cause is ... property has custom column name that is **camelCase** and **EntityIntrospector** doesn't apply naming strategy in this case"

Well, if you force a custom column name yourself with `@Column(name = "xxx")`, it makes sense **not** to apply naming strategy there.

When forcing a custom column name, you'd better know what you're doing. Naming strategy only applies for automatic name conversion

**Comment by doanduyhai** [comment]
If you want your custom column name to be case sensitive, escape it with double quote ("):

```java

public static final String COLUMN_NAME = "\"simpleName\"";
@Column(name = COLUMN_NAME)
private String name;
```

**Comment by vladimirdolzhenko** [comment]
It looks quite odd - to change naming convention is just add configuration property that makes lots of work in silence while changing domain model could be painful

**Comment by vladimirdolzhenko** [comment]
Ok - there are 2 points
- it has to be way to provide compatibility with existed scheme and custom column name - use column name w/o applying naming convention
- another point is to use the same constant as column name as use it the same for IndexedCondition - but I would not like to put naming convention into constant

**Comment by doanduyhai** [comment]
"it has to be way to provide compatibility with existed scheme and custom column name - use column name w/o applying naming convention" --> Adding a new naming strategy NONE which is just a pass through ?

**Comment by vladimirdolzhenko** [comment]
or maybe special flag in @Column like useNamingConvention that is **true** by default ?

**Comment by doanduyhai** [comment]
I don't like the idea of applying strategy to a custom column name.

The idea of custom column name is that the user knows what he is doing. It should be the "least surprise" principe that applies here.

Naming strategy is **magic**. It's fine to have magic applied automatically but when the user overrides the the default behavior by specifying himself the column name, we should not apply any magic.

**Comment by doanduyhai** [comment]
By the way, your reasoning is based on the fact that you use constants to specify custom column names on every field. Is there any reason for that ? Why don't you just name properly your Java fields and apply the appropriate naming strategy ?

Specifying custom column name with `@Column` should be exceptional, not the default behavior, just because it is tiresome

**Comment by vladimirdolzhenko** [comment]
My case is to have a consistency between model and IndexedCondition - that's why I exposed column name as constant - I'd like to have some technique to create IndexedCondition referring specific property.

**Comment by doanduyhai** [comment]
Fair enough. Unfortunately, right now Achilles does not provide any type-safe way to create index condition. 

Indeed the index condition is a very simple support for 2nd index because I believe they're should rarely be used. There are so many misuses of 2nd index that lead to severe performance degradation.

The next version of Achilles (4.0) will introduce major breaking change, with total type safety and compile time proxy generation (using Annotation Processing Tool). We can address properly the index condition then

**Comment by vladimirdolzhenko** [comment]
Ok, anyway wrong index name has to be fixed.

**Comment by doanduyhai** [comment]
Sure, the issue remains valid with regard to index name

**Comment by vladimirdolzhenko** [comment]
BTW. Regarding the issue of using constants in column name and indexedcondition - may be it is worth to put a suggestion / tip into the exception message ?

**Comment by doanduyhai** [comment]
By looking into the source code of **EntityMapper.mapRowToEntityWithPrimaryKey**, this method is only called by **typed queries**. And in the **AbstractTypedQuery** constructor:

```java

...
this.propertiesMap = transformPropertiesMap(meta);
```

```java
    private Map<String, PropertyMeta> transformPropertiesMap(EntityMeta meta) {
        Map<String, PropertyMeta> propertiesMap = new HashMap<>();
        for (PropertyMeta pm : meta.getPropertyMetas().values()) {
            String cqlColumnName = pm.getCQLColumnName();
            propertiesMap.put(cqlColumnName, pm);
        }
        return propertiesMap;
    }
```

So indeed we fetch already the correct column name. There is a small bug however, for columns with are _case sensitive_, they are escaped with double quotes so the corresponding key in the `propertiesMap` is something like "\"xxxx\"" but in the Java driver, `column.getName()` returns the un-escaped version ...

I need to remove the double quote escape when transforming the propertiesMap field name into CQL column name.
