### ISSUE TITLE
proxied setter of entity does not call setter implementation

### ISSUE THREAD

**Issue by sahlex** [doanduyhai/Achilles#199]
When having a non-trivial setter in an entity like
```
public void setPrice(int price) {
        // if price is changed, the sequence will change as well
        setSequence(UUIDs.timeBased());
        this.price = price;
    }
```
this code will never be called. The sequence property never changes when calling setPrice on a proxied  (managed) entity instance.

**Comment by doanduyhai** [comment]
Not an issue, please look at this link and my answer: https://github.com/doanduyhai/Achilles/issues/192

**Comment by sahlex** [comment]
Ok, thanks for the explanation. I'll work around this and try again with the 4.x version.
