### ISSUE TITLE
Batching and caching

### ISSUE THREAD

**Issue by vladimirdolzhenko** [doanduyhai/Achilles#203]
Is there any way to catch batch.flush() or batch.clear() with changed items (in specific batch).

Use case:
we do use @Caching annotation surrounded DAO methods (like findById, persist and delete).

In batch mode I'd like to be able to turn off (temporary) caching (or use old values) and put new values into cache when batch is flushed and don't put if batch has to cleaned.

**Comment by doanduyhai** [comment]
You can use the interceptor API.

In the standard interceptor API, the internal changeSet before the updates are not exposed as a public API.

 What you can do is to create an interceptor that extends the [AchillesInternalInterceptor](https://github.com/doanduyhai/Achilles/blob/master/achilles-core/src/main/java/info/archinnov/achilles/internal/interceptor/AchillesInternalInterceptor.java) and then play with the ChangeSet stored in the proxy.

As an example, you can look at this code: https://github.com/doanduyhai/Achilles/blob/master/achilles-core/src/main/java/info/archinnov/achilles/internal/interceptor/DefaultBeanValidationInterceptor.java
