### ISSUE TITLE
Null Pointer Exception for usecase: LWP +Embedded Id

### ISSUE THREAD

**Issue by rdhabalia** [doanduyhai/Achilles#207]
If given table has compoundKey which requires to create EmbeddedKey in Achilles-library.
Now, for given EmbeddedKey, we create below PropertyMeta object
and propertyMeta.getCQLColumnName() = NULL for any embeddedKey.
In that case, it is throwing Null-Pointer Exception.
It means, somehow we should ignore PropertyMeta check for EmbeddedKey.

https://github.com/doanduyhai/Achilles/blob/master/achilles-core/src/main/java/info/archinnov/achilles/internal/metadata/holder/EntityMetaTranscoder.java#L57

 private PropertyMeta findPropertyMetaByCQLName(String cqlName) {
        for (PropertyMeta propertyMeta : meta.getAllMetasExceptCounters()) {
            if (propertyMeta.getCQLColumnName().equals(cqlName) ) {
                return propertyMeta;
            }
        }

**Comment by doanduyhai** [comment]
You're right, there is a clear flaw here.
