### ISSUE TITLE
Interceptors do not support Entity inheritance.

### ISSUE THREAD

**Issue by amorillotraxens** [doanduyhai/Achilles#216]
It would be nice to be able to add interceptors on parent class entity.

**Comment by doanduyhai** [comment]
It is feasible, to be done for next release

**Comment by amorillotraxens** [comment]
Do you have any idea of the availability of the next release ?

**Comment by doanduyhai** [comment]
I'm OFF this week. I can make a release for you next week

**Comment by doanduyhai** [comment]
Fixed in Achilles 3.2.2

**Comment by amorillotraxens** [comment]
It works using the unit test environment (AchillesResource) but it does not seem to work with the PersistenceManagerFactory. My code is :

private final List<Interceptor<?>> interceptors;

		final PersistenceManagerFactory persistenceManagerFactory = PersistenceManagerFactoryBuilder
				.builder(this.cluster)
				.withEntities(this.entities)
		                .withEventInterceptors(this.interceptors)
				.withKeyspaceName(this.keySpace)
				.forceTableCreation(false)
				.build();

My interceptors are never called in that case. If I use the unit test framework, like this :
	@Rule
	public AchillesResource resource = AchillesResourceBuilder
			.withEntityClasses(getEntityClasses())
			.withKeyspaceName("test")
			.withInterceptors(this.interceptors)
			.truncateBeforeTest()
			.build();
My interceptors are called.

**Comment by doanduyhai** [comment]
I try to reproduce the issue using the PersistenceManagerFactoryBuilder and it worked for me:

```java
public class TestIT {

    private Cluster cluster = CassandraEmbeddedServerBuilder
            .noEntityPackages()
            .cleanDataFilesAtStartup(true)
            .withKeyspaceName("test_traxens")
            .buildNativeClusterOnly();

    private Interceptor<ParentEntity> interceptor = new Interceptor<ParentEntity>() {
        @Override
        public void onEvent(ParentEntity entity) {
            entity.setParentValue("post_insert_parent_and_children");
        }

        @Override
        public List<Event> events() {
            return Arrays.asList(POST_INSERT);
        }
    };

    private PersistenceManager manager;

    @Before
    public void setUp() {

        this.manager = PersistenceManagerFactoryBuilder
                .builder(this.cluster)
                .withEntities(Arrays.asList(CompleteBean.class, ParentEntity.class, ChildEntity.class))
                .withEventInterceptors(Arrays.<Interceptor<?>>asList(this.interceptor))
                .withKeyspaceName("test_traxens")
                .forceTableCreation(true)
                .build()
                .createPersistenceManager();
    }

    @Test
    public void should_apply_insert_interceptors_for_parent_and_children() throws Exception {
        //Given
        ParentEntity parentEntity = new ParentEntity(10L, "parentValue");
        ChildEntity childEntity = new ChildEntity(10L, "parentValue", "childValue");
        final Session session = manager.getNativeSession();

        //When
        manager.insert(parentEntity);
        manager.insert(childEntity);

        Row rowParent = session.execute("select parent_value from parent_entity where id = " + parentEntity.getId()).one();
        Row rowChild = session.execute("select parent_value from child_entity where id = " + childEntity.getId()).one();

        //Then
        assertThat(parentEntity.getParentValue()).isEqualTo("post_insert_parent_and_children");
        assertThat(childEntity.getParentValue()).isEqualTo("post_insert_parent_and_children");
        assertThat(rowParent.getString("parent_value")).isEqualTo("parentValue");
        assertThat(rowChild.getString("parent_value")).isEqualTo("parentValue");
    }
}
```

Can you please check that when you call `.withEventInterceptors(this.interceptors)`, the variable `this.interceptors` is initialized and not null ?

**Comment by amorillotraxens** [comment]
OK, I got it. You are right, it works. The problem is that I use an interceptor to set the partition key to a timeuuid. But the validation is done BEFORE the interceptors are called, as you can see in the following trace :

	java.lang.IllegalArgumentException: Cannot get primary key for entity com.traxens.traxhub.bean.cassandra.adminroot.ClientBean
	at info.archinnov.achilles.internal.persistence.operations.EntityValidator.validateEntity(EntityValidator.java:48)
	at info.archinnov.achilles.internal.persistence.operations.EntityValidator.validateEntity(EntityValidator.java:37)
	at info.archinnov.achilles.persistence.AbstractPersistenceManager.asyncInsert(AbstractPersistenceManager.java:79)
	at info.archinnov.achilles.persistence.CommonPersistenceManager.insert(CommonPersistenceManager.java:54)
	at com.amo.cassandra.achilles.TestITTrax.testInterceptClient(TestITTrax.java:71)

So, effectively, this issue is solved. Though, is there any way to set the partition key in an interceptor, before entity validation ?

**Comment by doanduyhai** [comment]
Columns that are part of primary key (partition key(s) and clustering column(s)) should not be modified by interceptors because the primary key is used to guarantee data integrity.

**Comment by amorillotraxens** [comment]
I understand that. Though, how can I assign a timeuuid primary key each time I want to execute an insert ? I would like to do the equivalent of a JPA @GeneratedValue. What is the best strategy in that case ?

**Comment by doanduyhai** [comment]
There is an utility method:  `com.datastax.driver.core.utils.UUIDS.timeBased()` that will generate automatically a timeUUID

Juste use it to create a new entity and do a manager.insert(newEntity)

**Comment by amorillotraxens** [comment]
That's what I try to do in the interceptor, so all my new insert will have a new generated timebased UUID. I wanted to factorize the job, instead of doing it for each entity.
