### ISSUE TITLE
Not Find Annotation for creating index on map key

### ISSUE THREAD

**Issue by gunjesh31** [doanduyhai/Achilles#220]
Hi 
I was writing java code where i need to create index on a map key. but i did not found any annotation in  Achilles for it like we use @index to create index on any normal column. 

Thanks
Gunjesh

**Comment by doanduyhai** [comment]
Please see this issue: https://github.com/doanduyhai/Achilles/issues/218

**Comment by doanduyhai** [comment]
Fixed in Achilles 4.0.0
