### ISSUE TITLE
Support for secondary index in DSL API

### ISSUE THREAD

**Issue by doanduyhai** [doanduyhai/Achilles#224]
```java

   @Column
   @Index
    private String country;

 
    manager
                  .dsl()
                  .select()
                  ....
                  .where()
                  .partitionKey_Eq(...)
                  .country_Eq(...)
                  ....

```

The secondary index query in the **[DSL API]** is only possible when the **partition key** is provided, for performance reason

[DSL API]: https://github.com/doanduyhai/Achilles/wiki/Manager-API#dsl

**Comment by kulfon** [comment]
> **partition key** is provided, for performance reason

But how about analytical, backend operations? I guess that warning about poor performance is enough

Moreover there is `SSTableAttachedSecondaryIndex` and imo it definitely deserves DSL api method. 
Can you reconsider?
