### ISSUE TITLE
Annotation @CompoundPrimaryKey has disappeared since Achilles 4.x

### ISSUE THREAD

**Issue by amorillotraxens** [doanduyhai/Achilles#247]
We used a lot this annotation with Achilles 3.x. This might stop us to migrate to 4.x. Is there any equivalent in Achilles 4.x ?

**Comment by doanduyhai** [comment]
You can read the migration guide: https://github.com/doanduyhai/Achilles/wiki/Migration-Guide

`@CompoundPrimaryKey` is removed, now you can use directly `@PartitionKey` and `@ClusteringColumn` in the entity without having to declare a separated class for the compound primary key

**Comment by amorillotraxens** [comment]
That's the point. I miss the @CompoundPrimaryKey. We set up an architecture based on Java Generics, and the key must be a separate class to achieve that.
For instance, we have a generic class AbstractDaoCRUD<K,B>, where K is the table key and B is the table content. Usgin generic, we  can define a method : 
public B save(final B bean) 
and another 
public B get(final K key).

This will not be possbile if the key is directly included in the bean. That's why we used the @CoupoundPrimeryKey.

**Comment by doanduyhai** [comment]
You can use inheritance with `@PartitionKey` and `@ClusteringColumn` to achieve the same effect to


```java

public class CompoundPK {

   @PartitionKey
   protected Long partition;
  
   @ClusteringColumn
   protected UUID clustering;
}

@Table
public ChildA extends CompoundPk {
     @Column
     private String value
}

@Table
public ChildB extends CompoundPk {
    @Column
    private Date date;
}
```

**Comment by doanduyhai** [comment]
Closing the issue if no more question
