### ISSUE TITLE
4.1.1 snapshot published?

### ISSUE THREAD

**Issue by reznet** [doanduyhai/Achilles#252]
Is the new 4.1.1 snapshot published anywhere?  We've found that it fixes a race condition in cassandra during shutdown, and would like to avoid cloning and publishing locally if it's already published.

**Comment by doanduyhai** [comment]
There will be a release very soon, in 2 days to be exact so don't worry

**Comment by reznet** [comment]
great!  looking forward to it

**Comment by doanduyhai** [comment]
4.2.0 is released with all the bug fixes
