### ISSUE TITLE
Cassandra synchronize a read or a write from all the running hosts.

### ISSUE THREAD

**Issue by goyalzz** [doanduyhai/Achilles#268]
Hi @doanduyhai ,

Cassandra itself does not offer any way to synchronize a read or a write from all the running hosts.
Is there any way to synchronize all read and write operations without [QCassandraLock](http://snapwebsites.org/mo_references_view/libQtCassandra-doc-0.4/classQtCassandra_1_1QCassandraLock.html#details "QCassandraLock")

**Comment by doanduyhai** [comment]
No, there is no way, because we don't want to resort to a **global lock**. Look at some other NoSQL DB where the do lock the whole database/collection, it's so terrible

**Comment by goyalzz** [comment]
If there is not way global lock then how we handle to access the tables in a synchronous way..
Let's assume that I created a user table in which user id is a partition key and user email and password column.
1000 threads access this table at same time to create a user but programmatically I check that there is no duplicate email so I reject these calls .. but at that time when 1000 threads calls at same time having same email id .. in that case how to handle these duplicate values without synchronous read and write tables.

**Comment by doanduyhai** [comment]
To avoid concurrent updates, you can use LightWeight Transactions, but it has a very expensive cost, it's up to you to decide wether it worths the effort

**Comment by goyalzz** [comment]
Thanks for the help.
