### ISSUE TITLE
Partition Key and DSL

### ISSUE THREAD

**Issue by heyitsaakash** [doanduyhai/Achilles#270]
In case of Composite Partition Key Cassandra 3.X onwards we have feature to query based on specific part . e.g for composite partition key (A,B) i can query specifically for A=xxxx and may not specify B.

But, achilles at present makes it mandatory in DSL to provide all the partition key parameters. E.g Below for partition key of (id, usertype) i can not query for only id I do need to specify userType too. Please update if we have missed something on our end.
	getRepositoryType().dsl().select().allColumns_From(provider).where().id().Eq(id).userType().Eq(UserType.EMPLOYEE).getOne();
provide provision to query

**Comment by doanduyhai** [comment]
> In case of Composite Partition Key Cassandra 3.X onwards we have feature to query based on specific part . e.g for composite partition key (A,B) i can query specifically for A=xxxx and may not specify B.

Wrong, if you don't provide B, Cassandra cannot compute the token value (because the token is computed using A **and** B) so Cassandra cannot know on which node the partition is located --> **full cluster scan**
