### ISSUE TITLE
Possible invalid @Counter error in 5.1.3

### ISSUE THREAD

**Issue by andrewv99** [doanduyhai/Achilles#273]
With Achilles 5.1.3,

The example in the @Counter documentation is:

@Column
@Counter
private Long count;

But if I try this (specifically because I want to set the column name):

@Column(value = "uc")
@Counter
private long updateCount;

I get an error, stating 'should not mix counter and normal columns'. 

Is this a correct constraint ?

Also, the page:
https://github.com/doanduyhai/Achilles/wiki/Achilles-Annotations says

"Below is a list of all Achilles annotations" but there is no documentation for @Counter.

Thanks

**Comment by doanduyhai** [comment]
What is the source code of your entity ?  `should not mix counter and normal columns` is very clear. You cannot have a normal column and a counter column inside the same table, it's  a limitation of Cassandra itself

**Comment by andrewv99** [comment]
Hi, I understand the Cassandra restriction/limitation to mentioned, the only reason I was using the @Column annotation, was becaue I wanted be able to explicitly set the name of the counter. Would it be possible to add an attribute to @Counter to set the generated name for it in the schema ?

**Comment by doanduyhai** [comment]
> Would it be possible to add an attribute to @Counter to set the generated name for it in the schema ?

It is and it should work this way, please post your entity source code

**Comment by andrewv99** [comment]
Hi,

Sorry I have been busy and have not replied earlier.

I am not sure if your last comment meant that @Counter has an attribute for the name, but there isn't one there:

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@Documented
public @interface Counter {

}

so, I assume you mean that it is possible to use @Column value attribute to set the column name.

Here is my entity source code tat causes the following error with Achilles 5.1.4:

package mypackage;

import java.io.Serializable;
import java.util.UUID;

import info.archinnov.achilles.annotations.Column;
import info.archinnov.achilles.annotations.Counter;
import info.archinnov.achilles.annotations.PartitionKey;
import info.archinnov.achilles.annotations.Table;
import info.archinnov.achilles.annotations.TimeUUID;

@Table(table = "mytable", keyspace = "mykeyspace")
public class MyEntity implements Serializable
{
	private static final long serialVersionUID = 1L;

	@PartitionKey(value = 1)
	@TimeUUID
	private UUID id;

	@Column(value = "nm")
	private String name;

	@Column(value = "uc")
	@Counter
	private long updateCount;

	public MyEntity()
	{
	}

	public UUID getId()
	{
		return id;
	}

	public void setId(final UUID id)
	{
		this.id = id;
	}

	public long getUpdateCount()
	{
		return updateCount;
	}

	public void setUpdateCount(final long updateCount)
	{
		this.updateCount = updateCount;
	}

	public String getName()
	{
		return name;
	}

	public void setName(final String name)
	{
		this.name = name;
	}

}

If I take out the name field, it compiles ok - I realized later that I had made the mistake of having a non primary key column in a table that had a counter, but I didn't previously understand that to be the issue from the generated error message:

error: Class 'mypackage.MyEntity' should not mix counter and normal columns
error: Error while parsing: Class 'mypackage.MyEntity' should not mix counter and normal columns

Would it be possible to change or add to the error message, to make it a little more specific for this type of error, ex. "Primary key columns are the only other columns that can be defined in a table with an @Counter column" ?

In any case, the @Counter annotation is now working ok for me.

Thanks for your assistance.

**Comment by doanduyhai** [comment]
The error message `Class 'mypackage.MyEntity' should not mix counter and normal columns` is very clear for anyone who has a little knowledge about Cassandra data modeling. Even the official documentation is clearly mentioning that: http://cassandra.apache.org/doc/latest/cql/types.html#counters

`A table that contains a counter can only contain counters. In other words, either all the columns of a table outside the PRIMARY KEY have the counter type, or none of them have it.`
