### ISSUE TITLE
Support naming customization for generated classes

### ISSUE THREAD

**Issue by vrudikov** [doanduyhai/Achilles#275]
It will be good to add a property to @CompileTimeConfig:
`@CompileTimeConfig(generatedNamesSeparartor = "_")`
`@CompileTimeConfig(generatedNamesSeparartor = "")`
`@CompileTimeConfig(generatedNamesSeparartor = "__")`
So we can skip underscore for generated classes. Sometimes it ruins codestyle... :)

I can implement PR

**Comment by doanduyhai** [comment]
1. Be careful that the user-defined separator should be compatible with Java class name restrictions

2. Add unit tests to validate error messages when user provides incorrect separator

3. Add at least an integration test in `integration-test-2_1` module

Your PR is welcomed!

**Comment by doanduyhai** [comment]
Closing this issue since generated classname undergoes heavy constraint: max 255 chars. See https://github.com/doanduyhai/Achilles/issues/293 for more details

**Comment by vrudikov** [comment]
Agree. Thanks for the update
