### ISSUE TITLE
How can i import CSV file data in Cassandra.

### ISSUE THREAD

**Issue by goyalzz** [doanduyhai/Achilles#278]
Hi @doanduyhai ,
Can you please help me that how can i run raw query `COPY airplanes (name, manufacturer, year, mach) FROM 'temp.csv';` in native session, it throws below error:
```
com.datastax.driver.core.exceptions.SyntaxError: line 1:0 no viable alternative at input 'COPY' ([COPY]...)
```

**Comment by goyalzz** [comment]
Hi @doanduyhai,
Can you please answer my question?

**Comment by doanduyhai** [comment]
`COPY` is a command of the shell `cqlsh`. COPY does not exist in standard CQL syntax ...
