### ISSUE TITLE
Support TOKEN function for partition keys. At least basic operators(=,<,>)

### ISSUE THREAD

**Issue by vrudikov** [doanduyhai/Achilles#284]
@doanduyhai hi! appreciate your work

Can't find how can i use Cassandra native TOKEN function for partition keys(and maybe for clustering too). For example i need to build select statement like this(https://docs.datastax.com/en/cql/3.1/cql/cql_using/paging_c.html):
```
SELECT * FROM customers WHERE TOKEN(id) > TOKEN(a98d0f15-aad2-4a50-94b6-8aa4e2ede079);
```
But i see only 3 available options in DSL:
```
customerManager.dsl().select().allColumns_FromBaseTable().where().id().Eq()
customerManager.dsl().select().allColumns_FromBaseTable().where().id().Eq_FromJson()
customerManager.dsl().select().allColumns_FromBaseTable().where().id().IN()
```

We have 2 options here:
1) Add Token call as different Relation:
```
customerManager.dsl().select().allColumns_FromBaseTable().where().idToken().Eq()
customerManager.dsl().select().allColumns_FromBaseTable().where().idToken().Gt()
...
```
2) Add "token" method to "id" relation:
```
customerManager.dsl().select().allColumns_FromBaseTable().where().id().token().Eq()
customerManager.dsl().select().allColumns_FromBaseTable().where().id().token().Gt()
...
```

@doanduyhai can you point me out to class where i can implement it? Is it SelectWhereDSLCodeGen class?
And what is the best option to do it?

**Comment by doanduyhai** [comment]
@vrudikov  I guess adding `token()` method to `id()` relation class is cleaner.

To add this feature, you need to look at the method `SelectWhereDSLCodeGen:: buildSelectWhereForPartitionKey()` here: https://github.com/doanduyhai/Achilles/blob/master/achilles-core/src/main/java/info/archinnov/achilles/internals/codegen/dsl/select/SelectWhereDSLCodeGen.java#L189-L190

You will need to add some code to:

- build a new internal class called `<partition_key_name>_Token_Relation` (use `TypeSpec.builder()`)
- build a new method `token()` that returns a new instance of the above class
- inside this new internal class, build the methods `eq()`, `gt()`, `gte()`, `lt()`, `lte()` all taking `java.util.Long` as parameter and return type is the variable `relationClassTypeName` already created inside the method  `buildSelectWhereForPartitionKey()`

**Comment by vrudikov** [comment]
@doanduyhai wow. nice. appreciate your help. will be very glad if you will guide me through this.
ok. it's time to dig the code

**Comment by vrudikov** [comment]
@doanduyhai can i write a test and call buildSelectWhereForPartitionKey method and see results immediately? SelectWhereDSLCodeGen is abstract and implementation is generated during build. Can't understand how should i test it

**Comment by doanduyhai** [comment]
The best unit test is to see the **generated code** compile without error

Alternatively, you can also force the code generation to a String and assert the string content, see this class https://github.com/doanduyhai/Achilles/blob/master/achilles-core/src/test/java/info/archinnov/achilles/internals/codegen/ManagerCodeGenTest.java

**Comment by vrudikov** [comment]
@doanduyhai I'm trying to run tests, but can't get rid of compilation time errors
![screenshot at feb 03 09-50-00](https://cloud.githubusercontent.com/assets/493714/22582231/36cd0072-e9ee-11e6-8416-8072b95edbe1.png)

**Comment by doanduyhai** [comment]
@vrudikov 

`mvn clean` first to remove existing  generated code

**Comment by doanduyhai** [comment]
@vrudikov Any news on this subject ? Did you succeed to compile ?

**Comment by vrudikov** [comment]
@doanduyhai yes. i forgot to mention that Maven compile works as designed and is success. It was Intellij compilation. I added some code to SelectWhereDSLCodeGen, but haven't any time to proceed. Will take a look today. Thanks for checking me

**Comment by doanduyhai** [comment]
@vrudikov Sometimes IntelliJ has issues to refresh generated data.  The fix is simple, delete completely the `target/generated-sources/annotations/` folder and force a rebuild to regenerate from scratch the code

**Comment by vrudikov** [comment]
@doanduyhai i found what was the cause of Intellij IDEA compilation issue:
Annotation processor was enabled by default for Intellij because of Maven settings
I disabled it and now Intellij module compiles successfuly and i can run tests

![pasted image at 2017_02_09 04_04 pm](https://cloud.githubusercontent.com/assets/493714/22784698/bfc15ba4-eed9-11e6-9c94-1a7bcdea6e85.png)

**Comment by doanduyhai** [comment]
Good to know, IntelliJ is sometimes **too** smart and enable options automatically

**Comment by vrudikov** [comment]
So here is my first attempt. Need to finish a lot from your guide above. But i'm on the right way

![image](https://cloud.githubusercontent.com/assets/493714/22788117/4c751344-eee7-11e6-9809-7b35bc305f4a.png)

**Comment by doanduyhai** [comment]
I just realize there is a big problem

if you have only 1 partition key, easy:

```java
    manager.dsl()
        .select()
        .allColumns_FromBaseTable()
        .where()
        .partitionKey().Token().Eq(....)
```

Now if you have more than 1 partition key and at least 1 clustering column:

```java
    manager.dsl()
        .select()
        .allColumns_FromBaseTable()
        .where()
        .partitionKey1().Eq(....)
        .partitionKey2().Eq(....)
        .clusteringColum().Eq(....)
```

With the `token` function, we should create a Builder path to go directly from `where().Token().Eq(...)` to `clusteringColumn()` without having to provide `partitionKey2().Eq(...)`


```java
    manager.dsl()
        .select()
        .allColumns_FromBaseTable()
        .where()
        .token().Eq(....)  <-- BY PASS ALL PARTITION KEYS RELATION
        .clusteringColum().Eq(....)
```

And that by-passing is really tricky to be implemented, but still possible

So after the `where()` method, we should provide 2 choices:

* either the normal path with `partitionKey1() -> partitionKey2() -> clusteringColum()`
* or the token path with `token() -> clusteringColumn()`

It implies that the Token_Relation class should **not** be put inside a partitionKey_relation class but outside

See the idea ?

**Comment by vrudikov** [comment]
yeah. understand. so we need to have 2 options impltemented:
1) partitionKey1().Token().eq() -> partitionKey2() -> clusteringColum1()
2) partitionKey1().Token().eq() -> clusteringColum1()

Right?

**Comment by doanduyhai** [comment]
No, it should be

1. `where().parttonKey1()...->partitionKey2()...->clusteringColumn()` or
2. `where().token()...->clusteringColumn()`

In the 2nd scenario, there is no `partitionKey1()` or  `partitionKey2()` because the given token value is indeed a hash of all partition keys.

By the way, in addition to `token().Eq(..)` and `token().In(..)` we should also add `token().Gt(..)`, `token().Gte(..)`, `token().Lt(..)`, `token().Lte(..)`, `token().Gt_And_Lt(..)`  etc.

**Comment by vrudikov** [comment]
Ok. I think i understood. I got this error: "The token() function must be applied to all partition key components or none of them" when tried to apply token to only 1 of 4 partition keys. So it is the Cassandra rule
Now it's clear for me.

**Comment by vrudikov** [comment]
Hi, doanduyhai. i'm still here and still want this feature to be implemented. Was busy, will continue development soon

**Comment by doanduyhai** [comment]
Thanks for the update!

**Comment by vrudikov** [comment]
@doanduyhai WOW! Great job. I looked at the code and realized for me it's very complex thing :) Thanks for implementation. When it's gonna be available in Maven central?

**Comment by doanduyhai** [comment]
So I need to add support for GROUP BY clause recently available in latest Cassandra version and after that we're good for another release

There is also a project to write a comprehensive contributor guide that explains all the internal architecture of Achilles so that makes life easier for external contributors.

**Comment by vrudikov** [comment]
> There is also a project to write a comprehensive contributor guide that explains all the internal architecture of Achilles so that makes life easier for external contributors.
AWESOME!
