### ISSUE TITLE
info.archinnov.achilles.configuration.ArgumentExtractor#initSession should use the session only and not the cluster

### ISSUE THREAD

**Issue by rmannibucau** [doanduyhai/Achilles#285]
Hi

when passing a native session, info.archinnov.achilles.configuration.ArgumentExtractor#initSession shouldn't call connect on the cluster and therefore should use orElseGet instead of orElse

**Comment by doanduyhai** [comment]
Ok but if you use `orElseGet` you need to pass in a `Supplier<Session>`

So the question is what to put in the `Supplier` ? `cluster.connect()` ?

**Comment by rmannibucau** [comment]
cluster::connect yes which will be called lazily instead of being called whatever is set as session

assuming you pass the session as param, current code does:

    session = get(SESSION);
    if (session == null) {
        session = cluster.connect();
    } else {
        cluster.connect();
    }

vs (orElseGet())

    session = get(SESSION);
    if (session == null) {
        session = cluster.connect();
    }

**Comment by doanduyhai** [comment]
Ok I get your point, the `orElse()` block is evaluated right away even if the Session object is present. Can you please do a small PR to fix this ?

**Comment by rmannibucau** [comment]
here it is https://github.com/doanduyhai/Achilles/pull/286
