### ISSUE TITLE
Configurable results/rows displayed with DML Logger

### ISSUE THREAD

**Issue by mykapp** [doanduyhai/Achilles#287]
Hi @doanduyhai 
Thanks for your great job with Achilles.
I have an improvement proposition about the ACHILLES DML Logger (if this is not possible yet).

Currently, when we activate the DEBUG Level for ACHILLES_DML_STATEMENT, we automatically have :
- information about the executed Query (Query ID / QueryString / consistency Level / Java bound values / Encoded bound values)
- information about the resultset (columns with their type / Query ID / 10 first result)

It would be great if we could configure this to display or not the results. Or even better to choose the number of row displayed in the results.

Is it currently possible to configure it this way? Otherwise do you think it would be possible in a future version?

**Comment by doanduyhai** [comment]
_It would be great if we could configure this to display or not the results. Or even better to choose the number of row displayed in the results._

It can certainly be done. How ? By introducing 2 new configuration parameters:

* achilles.dml.display_results: true/false
* achilles.dml.display_results.size: integer

For performance reason, I will still put a **hard** limit of max 100 rows to be displayed. It does not make any sense to display 1000 rows in a log

**Comment by mykapp** [comment]
_For performance reason, I will still put a hard limit of max 100 rows to be displayed._

I agree, my concern is to reduce the number of row displayed not increasing. Having a max limit makes sense.

Thanks

**Comment by doanduyhai** [comment]
Done, `achilles.dml.display_results.size = 0` means disable returned results display

**Comment by doanduyhai** [comment]
https://github.com/doanduyhai/Achilles/wiki/Statements-Logging-and-Tracing#limiting-the-number-of-displayed-returned-rows-for-dml-statement
