### ISSUE TITLE
Shorten generated class names

### ISSUE THREAD

**Issue by toadzky** [doanduyhai/Achilles#293]
Since generated DSL class names are created by concatenating primary key fields, when a class has multiple primary key fields that are descriptively named, the generated code fails to compile because the class name is too long.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project core-data-session-router-entities: Compilation failure
[ERROR] /development/core-data/session-router-entities/target/generated-sources/annotations/info/archinnov/achilles/generated/dsl/ConditionByGotoDestinationEntity_Select.java:[8913,17] error: error while writing ConditionByGotoDestinationEntity_Select.ConditionByGotoDestinationEntity_SelectWhereTypedMap_GotoDestinationType.gotoDestinationType_And_gotoDestinationAddress_And_destinationGroupAddress_And_destinationType_And_destinationAddress_And_identifier_Relation: /development/core-data/session-router-entities/target/classes/info/archinnov/achilles/generated/dsl/ConditionByGotoDestinationEntity_Select$ConditionByGotoDestinationEntity_SelectWhereTypedMap_GotoDestinationType$gotoDestinationType_And_gotoDestinationAddress_And_destinationGroupAddress_And_destinationType_And_destinationAddress_And_identifier_Relation.class (File name too long)
```

**Comment by doanduyhai** [comment]
Are you using *Windows* ?

**Comment by toadzky** [comment]
Nope, I'm on a Mac. I'm pretty sure it's a JVM limitation. I would guess it
might be related to Windows limitations but it's a cross platform issue.

**Comment by doanduyhai** [comment]
So your generated class name is: 

`ConditionByGotoDestinationEntity_Select$ConditionByGotoDestinationEntity_SelectWhereTypedMap_GotoDestinationType$gotoDestinationType_And_gotoDestinationAddress_And_destinationGroupAddress_And_destinationType_And_destinationAddress_And_identifier_Relation`

It has 255 characters. The Java specs says that your class name can have up to 65535 characters: http://stackoverflow.com/questions/1039029/does-java-have-a-limit-on-the-class-name-length

Indeed you're on Mac and the max allowed filename length is 255 characters with HFS+ filesystem, see here: http://apple.stackexchange.com/questions/86611/does-os-x-enforce-a-maximum-filename-length-or-character-restriction

**Comment by toadzky** [comment]
it's definitely still a bug because it means you can run it on a mac. that's a supported platform right?

**Comment by doanduyhai** [comment]
Humm, fair enough but my problem is how to shorten the classname without loosing its semantics ...

**Comment by doanduyhai** [comment]
Ohhhh, idea !

How about adding a new `@AchillesCompileTimeConfig` attribute to force Achilles to use randomly generated short name instead of using the natural name ? 

So that if you're on MAC it should do the job !

@toadzky

**Comment by toadzky** [comment]
You should probably make it the default configuration with an option to override. Based on a wikipedia comparison of file systems, exFAT, NTFS, ext2/3/4, ZFS, and several others all have the same 255 character filename limit.

**Comment by doanduyhai** [comment]
thanks for the link
