### ISSUE TITLE
No native support for slice Deletes

### ISSUE THREAD

**Issue by kevinmic** [doanduyhai/Achilles#295]
If I have the following class definition

```
@Table(table="MyTable")
public class MyTable {
    @PartitionKey
    private String pKey;

    @ClusteringColumn
    private String cColumn1;

    @ClusteringColumn(2)
    private String cColumn2
}
```

Now if I want to delete an entire partition / cusltering column out of the database I would write this query.
```
delete from MyTable where pKey = 'MyKey' and cColumn1 = 'MyCol';
```

Trying to represent this query in Achilles dsl doesn't work.
```
MyTable_Manager.dsl().delete().allColumns_FromBaseTable().where().pKey().Eq("MyKey").cColumn1().Eq("MyCol") -- No execute at this point
```

The dsl delete requires me to send in all keys rather than just the partitionkey or partition key and some (not all) of the clustering columns.

Am I missing something?   Is there a reason this isn't supported?   Looking at the select side it allows a slice query using just the partition key or partitionKey and some clustering columns.
```
MyTable_Manager.dsl().select().allColumns_FromBaseTable().where().pKey().Eq("MyKey").cColumn1().Eq("MyCol").getList();
```

**Comment by doanduyhai** [comment]
Did you try to execute your `delete from MyTable where pKey = 'MyKey' and cColumn1 = 'MyCol';` directly in **cqlsh** ? If it does not work in **cqlsh** it means it is a Cassandra restriction and not Achilles restriction

**Comment by kevinmic** [comment]
I have created a github project that demonstrates the issue.

[https://github.com/kevinmic/achilles-bug](https://github.com/kevinmic/achilles-bug)

In MyTableDao.deleteByPartitionId_usingAchilles and MyTableDao.deleteByPartitionId_usingDatastax I show what I CAN do with using datastax directly, but Achilles does not support.

```
    public void deleteByPartitionId_usingAchilles(String pKey) {
//      Does Not Compile, I am force to pass the entire key before I can execute
//      myTable_manager.dsl().delete().allColumns_FromBaseTable().where().myKey().Eq(pKey).execute();

//      This does compile, but forces me to specify the entire key, not just the partitionKey
        myTable_manager.dsl().delete().allColumns_FromBaseTable().where().myKey().Eq(pKey).myCCol1().Eq("COL").myCCol2().Eq("COL2").execute();

    }

    public void deleteByPartitionId_usingDatastax(String pKey) {
//      This works just fine in my test
        myTable_manager.getNativeSession().execute(
                QueryBuilder.delete().from(MyTable.TABLE_NAME).where(QueryBuilder.eq("myKey", pKey))
        );
    }
```

**Comment by doanduyhai** [comment]
You're slice, Achilles should allow slice **DELETE**
