### ISSUE TITLE
Stop including test dependencies as real dependencies

### ISSUE THREAD

**Issue by toadzky** [doanduyhai/Achilles#300]
This practice is frustrating because it bloats application jars with thing that shouldn't be there. It also is a pain because you have to be very careful with imports to make sure you aren't importing classes from test dependencies. An example is the `Strings` class, which is in both Guava and AssertJ. The link points at the part of the pom that should have a `<scope>test</scope>` added.

https://github.com/doanduyhai/Achilles/blob/master/pom.xml#L447-L449

**Comment by doanduyhai** [comment]
feel free to do a PR to add `<scope>test</scope>` to all test dependencies in the master pom
