### ISSUE TITLE
try to get 1 million data from cassendra but only able to fetch 5000

### ISSUE THREAD

**Issue by aruntanwar3** [doanduyhai/Achilles#301]
getRepositoryType().dsl().select().allColumns_From(provider).without_WHERE_Clause().getList();
this code show only 5000 data

**Comment by lmammino** [comment]
You are very likely using cassandra auto-paging option ([Ref](https://www.datastax.com/dev/blog/client-side-improvements-in-cassandra-2-0))

**Comment by doanduyhai** [comment]
You should use an `Iterator<???>` to fetch all rows rather than using `getList()` because there is a default limit of 5000 or something similar set at the driver side, which corresponds to 1 page worth of data

**Comment by doanduyhai** [comment]
```java

Iterator<Entity> iterator = getRepositoryType().dsl().select().allColumns_From(provider).without_WHERE_Clause().iterator()
while(iterator.hasNext()) {
 Entity entity = iterator.next();
 ...

}

```
