### ISSUE TITLE
Using "crud().updateStatic()" always include a "USING TTL=0" even when TTL is not set

### ISSUE THREAD

**Issue by mykapp** [doanduyhai/Achilles#303]
Hi, 
I am using the following code to update static column of a table :

```
Person_Manager person_manager = managerFactory.forPerson();
Person p = new Person();
p.setStaticDate(new Date(System.currentTimeMillis()));
p.setUserUid("myuseruid")
mgr.crud().updateStatic(p).generateAndGetBoundStatement();
```
As you can see I don't set the TTL in the query. But When I look at the statement that is generated I have the following trace :

`UPDATE ks.person USING TTL :ttl SET static_date=:static_date WHERE user_uid=:user_uid; { [ttl:0][static_date:Fri Apr 28 15:56:23 CEST 2017][user_uid:myuseruid] }`

There is an issue because I expect the TTL to be set only when I use the method ".usingTimeToLive()" and I didn't use it here.

Regards

**Comment by doanduyhai** [comment]
Not a problem. Setting TTL = 0 means `no TTL` for Cassandra

**Comment by mykapp** [comment]
Ok, thanks.
That's good to know. 
However I still found it strange to have a CQL BoundStatement generated with something I didn't asked.

**Comment by doanduyhai** [comment]
It's just an impl detail, it avoid to prepare 2 queries, one without TTL and one with TTL
