### ISSUE TITLE
It would be nice if there was significant information added to the info message

### ISSUE THREAD

**Issue by AndyGee** [doanduyhai/Achilles#314]
https://github.com/doanduyhai/Achilles/blob/81d6174f7245a9730e81d35fa1c9ff899ca8b925/achilles-core/src/main/java/info/archinnov/achilles/internals/context/ConfigurationContext.java#L294

...
[..] INFO - Start injecting dependencies to meta classes
[..] INFO - Start injecting dependencies to meta classes
[..] INFO - Start injecting dependencies to meta classes
[..] INFO - Start injecting dependencies to meta classes
...

This produces quite a number of log entries (50+ in our app) that doesn't really provide any useful information.
I'd like to suggest either reducing it to debug, or adding the entity information.

**Comment by doanduyhai** [comment]
Agree to reduce it to DEBUG. Indeed this log message is only there to inform the users on which stage the bootstrapping is currently

**Comment by AndyGee** [comment]
+1
