### ISSUE TITLE
range queries for multiple clustering columns possible with Achilles?

### ISSUE THREAD

**Issue by sweetacaro** [doanduyhai/Achilles#316]
First, thank you @doanduyhai for your work!
While writing a dsl().select() query for a table with multiple clustering columns, Achilles
suggested me a method that could range-query my 2 clustering columns:
```
manager
            .dsl()
            .select()
            .allColumns_FromBaseTable()
            .where()
            .partitionKey().Eq(2)
            .clustering1_And_clustering2().Gt_And_Lt(clustering1_Gt, clustering2_Gt, clustering1_Lt, clustering2_Lt)
            .getList();
```
which was surprizing because i've always been told that a such query is not possible.Indeed, while trying it, Cassandra and/or Achilles didn't take into account the 2nd clustering key, without getting any warning or exception from Achilles.
So my question is: is it a bug or is it here because it will possible to do such queries in a future release of Cassandra? Thx in advance

config:
Achilles 5.2.0
Cassandra driver 3.1.3
Cassandra 3.10

**Comment by doanduyhai** [comment]
Look at the generated Javadoc on the method `Gt_And_Lt ()`.

`clustering1_And_clustering2().Gt_And_Lt(...)` translates to 

`SELECT .. FROM ... WHERE partitionKey=2 AND (clustering1,clustering2) > ? AND (clustering1,clustering2) < ?`

The tuple notation is allowed in Cassandra since a while

**Comment by sweetacaro** [comment]
I was not aware of that "tuple" query. That's why I misinterpreted it like a multiple range query.
Thx for the clarification
