### ISSUE TITLE
[All] Start embedded Cassandra using in memory VFS to speed up tests

### ISSUE THREAD

**Issue by doanduyhai** [doanduyhai/Achilles#32]
For JUnit tests we are using an embedded Cassandra but it still dumps data on disk. Between each test, there may be truncate operations to clean up data.

 Truncate is very expensive and the test suite can takes over 10 secs to run if we are truncating several column families.

 The idea would be to use an in memory virtual file system and automatically truncate all  managed tables/column families (this point should be optional thpugh).

**Comment by mddubey** [comment]
Did you get a solution for this, I'm facing the same problem, using embedded-cassandra for integration tests. It takes a very long time.

**Comment by doanduyhai** [comment]
No there is no solution on **Achilles** side. I have noticed that schema execution is **slower** in Cassandra 3.x branch, because creating schema now trigger schema agreement on  Cassandra side.

That being said, since `CassandraEmbeddedServerBuilder ` allows you to configure data file folder and commitlog folder, you can easily bootstrap an in-memory virtual file system, map it to some path (like `/var/lib/memory/`) and then inject it into Achilles:


```java

CassandraEmbeddedServerBuilder
        .builder()
        .withClusterName("Test Cluster")
        .withDataFolder("/var/lib/memory/data")
        .withCommitLogFolder("/var/lib/memory/commitlog")
        .withSavedCachesFolder("/var/lib/memory/saved_caches")
        ...

```

**Comment by doanduyhai** [comment]
The in-memory thing can be done by **Achilles** but I try to limit the number of  **external** library dependencies. Therefore the `CassandraEmbeddedServerBuilder ` exposes the necessary extension points for pluggability and configuration
