### ISSUE TITLE
get total number of pages

### ISSUE THREAD

**Issue by fortm** [doanduyhai/Achilles#322]
Using withFetchSize, withPagingState and getListWithStats, it is possible to implement pagination using achilles. But to display total number of pages, so that on client side we can show - Showing page 2 of 10 ( in this case total pages =10 ) - does getListWithStats also expose that metric ?

**Comment by doanduyhai** [comment]
It is just technically impossible to have the total page count. We're using a distributed system and there is no lock on the database so basically new data can come in while you're iterating through the pages.
