### ISSUE TITLE
@achillesbeanmappingexception for the UDT

### ISSUE THREAD

**Issue by nicebalu** [doanduyhai/Achilles#326]
@achillesbeanmappingexception for the UDT

Caused by: info.archinnov.achilles.exception.AchillesBeanMappingException: Data type 'map<text, frozen<r2d2application.r2d2_udt>>' for column 'mappings' of entity 'class ItemIdR2D2' does not match type in live schema 'map<text, frozen<r2d2application.r2d2_udt>>'

![image](https://user-images.githubusercontent.com/19192497/35547118-1aaadb76-052c-11e8-8ef0-7262be77d633.png)

![image](https://user-images.githubusercontent.com/19192497/35547124-22b213a2-052c-11e8-97de-ca085a2f9bbf.png)

**Comment by nicebalu** [comment]
Can someone please look into this

**Comment by doanduyhai** [comment]
Which version of Achilles ? Can you please provide the complete stack-trace ?

**Comment by nicebalu** [comment]
it is 5.3.1

Also when I force created the schema by Achillies then it worked.

**Comment by doanduyhai** [comment]
I really need the full stack trace to start digging into the debug

**Comment by doanduyhai** [comment]
Closing if no further info to reproduce the issue
