### ISSUE TITLE
Port scans are invoked despite pre-set values

### ISSUE THREAD

**Issue by hubpan** [doanduyhai/Achilles#327]
I noticed that embedded cassandra attempted to scan a range of ports for Thrift, despite there is a defined value set at the builder. 

This seems to be related to a "side-effect" coming from `Optional.orElse()`, where the else case is always evaluated.
 
See:
[Link to source](https://github.com/doanduyhai/Achilles/blob/master/achilles-embedded/src/main/java/info/archinnov/achilles/embedded/ServerStarter.java#L269)

[Stackoverflow reference](https://stackoverflow.com/questions/33170109/difference-between-optional-orelse-and-optional-orelseget)

The quick fix is to simply change them to `orElseGet` and wrap the existing function calls with a supplier (i.e. () -> blah)
If you like this idea, I could submit a PR that updates that particular function in ServerStarter.java

**Comment by doanduyhai** [comment]
+1 for the PR

**Comment by hubpan** [comment]
Sorry for the delay, the required changes are simple (see #328) ... but I wasn't able to run all the tests in my new environment due to latest java sdk version and window bash. 

The CI build passed. However, I am not sure if that runs the tests under embedded module. If you have a working environment, you might want to run those tests against the branch from that PR. 

Really appreciate the work you have done with this project. It helps us a lot with our dev environment.

**Comment by doanduyhai** [comment]
Thanks for the PR
