### ISSUE TITLE
Codec is not called when deserializing null value

### ISSUE THREAD

**Issue by ylegat** [doanduyhai/Achilles#330]
Hello!

It appears that codecs are not used when deserializing `null` values:
[AbstractProperty](https://github.com/doanduyhai/Achilles/tree/achilles-5.3.1/achilles-core/src/main/java/info/archinnov/achilles/internals/metamodel/AbstractProperty.java#L130) define `decodeFromGettable` as:
```java
    public VALUEFROM decodeFromGettable(GettableData gettableData) {
        if (gettableData.isNull(NamingHelper.maybeQuote(getColumnForSelect())) && !isOptional()) return null;
        return decodeFromGettableInternal(gettableData);
    }
```

which will not call `decodeFromGettableInternal` when cassandra value is `null` and field is not optional (a constant in [SimpleProperty](https://github.com/doanduyhai/Achilles/tree/achilles-5.3.1/achilles-core/src/main/java/info/archinnov/achilles/internals/metamodel/SimpleProperty.java#L72))

This behavior is not adapted when the target class implement the [Null Object Pattern](https://en.wikipedia.org/wiki/Null_object_pattern), meaning: a null value is not represented by a null reference.

Do you think it would be possible to handle such a case? Maybe by adding a flag in `@Codec` telling that the decoder should always be called?

**Comment by doanduyhai** [comment]
Why don't you just use `Optional<TYPE>` and handle the null case with `!optional.isPresent()`  instead ????

**Comment by doanduyhai** [comment]
Note: `Optional` and `@Codec` can be used together

**Comment by doanduyhai** [comment]
Closing as it is not a design issue
