### ISSUE TITLE
Provide support for having same column as clustering key and secondary index in cassandra

### ISSUE THREAD

**Issue by Sachinbihade** [doanduyhai/Achilles#333]
cassandra do provide this feature of having same column as clustering key and secondary index. But achilles have no such feature. Can you please provide this feature ASAP.

**Comment by doanduyhai** [comment]
supporting this feature would require a rework on the DSL to avoid name clashing when using clustering column with normal CQL syntax and with secondary index syntax

**Comment by doanduyhai** [comment]
Fixed in Achilles 6.0.0
