### ISSUE TITLE
How to get result from conditional update

### ISSUE THREAD

**Issue by wittyameta** [doanduyhai/Achilles#343]
I tried using a custom ResultListener, but it doesn't always work correctly.

```
public class ResultListener implements LWTResultListener {

  private boolean applied;

  @Override
  public void onSuccess() {
     applied = true;
  }

  @Override
  public void onError(LWTResult lwtResult) {
    applied = false;
  }

  public boolean isApplied() {
    return applied;
  }
}
```
From my caller class, I call `isApplied()` but it seems that the `onSuccess` method is called asynchronously. The caller class doesn't see the updated value of `applied` field

**Comment by doanduyhai** [comment]
I understand your problem but it's the nature of asynchronous execution. To solve this, in my integration test, I have the following pattern:

```java

  final CountDownLatch latch = new CountDownLatch(1);
  final AtomicBoolean success = new AtomicBoolean(false);

 //When
        manager
                .dsl()
                .update()
                .fromBaseTable()
                 ...
                .withLwtResultListener(new LWTResultListener() {
                    @Override
                    public void onSuccess() {
                        success.getAndSet(true);
                    }

                    @Override
                    public void onError(LWTResult lwtResult) {
                    }
                })
                .withResultSetAsyncListener(rs -> {
                    latch.countDown();
                    return rs;
                })
                .executeAsync();

        //Then
        latch.await();
       assertThat(success.get()).isTrue();
```

First I declare 2 variables:

* a countdown latch, to be triggered when the ResultSet is available asynchronously
* an atomic boolean (or any `AtomicXXXX` class) that is by nature *thread-safe* to update the result of the asynchronous operation

With `withLwtResultListener()` I passed in an instance of `LWTResultListener` to set the atomic boolean value to `true`

However, if you *only* do that, the main thread will call immediately `assertThat(success.get()).isTrue()` before the `LWTResultListener` has a chance to be called ...

Therefore I need to add an `withResultSetAsyncListener()` to trigger the latch count down when the result set is available asynchronously.

In the main execution thread, I block on `latch.await()` until the `latch.countDown()` is called.

You can adapt this pattern to your use-case

**Comment by wittyameta** [comment]
Thanks!
