### ISSUE TITLE
Add support for specifying the name of the getter and setter that corresponds to a mapped field.

### ISSUE THREAD

**Issue by ccarpenter04** [doanduyhai/Achilles#347]
It would be nice to be able to specify the name of the getter and setter that corresponds to mapped fields instead of Achilles making the assumption that all getters and setters will use javabean-style naming conventions. For example, for part of my project we're using fields of type Boolean (not the primitive). For these fields, my team decided to use the isX naming convention even though it's debatable whether or not that actually conforms to javabean naming conventions. It would be nice to be able to specify the name of the getter/setter directly instead of being forced into using naming conventions that deriveGetterName/deriveSetterName are capable of deriving from the fieldName.

**Comment by doanduyhai** [comment]
Better idea, forget about getter/setter and embrace immutability:

https://github.com/doanduyhai/Achilles/wiki/Table-Mapping#immutable-entity

https://github.com/doanduyhai/Achilles/wiki/Achilles-Annotations#entitycreator

**Comment by ccarpenter04** [comment]
Unfortunately that's not a change I can make, I considered it before making this issue.

**Comment by doanduyhai** [comment]
In this case, instead of bending **Achilles**, try this pattern:

**Comment by ccarpenter04** [comment]
I can do that, it just creates some redundancy. Is there a reason you're so against expanding Achilles to have this functionality? It seems like a pretty basic request with use cases. It would just be a matter of making it read a value from an annotation instead of using the deriveGetterName/deriveSetterName methods. It would allow developers to have more control.

**Comment by doanduyhai** [comment]
I don't want **Achilles** to become like Jackson with plenty of different ways to do the same thing. Java beans convention support and immutable entity support is _good enough_ for 90% of use cases

**Comment by ccarpenter04** [comment]
This isn't just adding a new way to do the same thing though, there is currently no way to provide the name of a getter and setter for a given field. That's something rather basic that in my opinion should be customizable, because modifying the naming conventions being used by an entire project is not always viable.

**Comment by doanduyhai** [comment]
If you really want this feature for **your** team, you're welcomed to push a pull-request.

For the record, the parsing of getter is done here: https://github.com/doanduyhai/Achilles/blob/master/achilles-core/src/main/java/info/archinnov/achilles/internals/apt/AptUtils.java#L444-L455
