### ISSUE TITLE
How to assure the annotationProcessor get triggered using gradle?

### ISSUE THREAD

**Issue by yahudev** [doanduyhai/Achilles#350]
I'm using gradle 4.10.2, configured as follow but the annotation processor doesn't get triggered on `./gradlew clean compileJava` task
```
dependencies {
   annotationProcessor 'info.archinnov:achilles-core:5.3.1'
   compileOnly 'info.archinnov:achilles-core:5.3.1'
}
```

**Comment by doanduyhai** [comment]
Please read the exchange in this issue and try the proposed solution: https://github.com/doanduyhai/Achilles/issues/261
