### ISSUE TITLE
Table_Select.W always returns default cluster (1)

### ISSUE THREAD

**Issue by RaAleks** [doanduyhai/Achilles#352]
Hi @doanduyhai, i have a table such as below.  So i want that Achilles returns me table with cluster2 in descending order. But Table_Select.W always returns W_Cluster1, that's why i can't see ability to set descending order for my second cluster. Also below code for test manager what i want to have.

@Table(table = "test_table")
public class TestTable {

    @PartitionKey
    private String partition;

    @ClusteringColumn
    private String cluster1;

    @ClusteringColumn(value = 2, asc = false)
    private Date cluster2;
}

`testTable_manager
                .dsl()
                .select()
                .allColumns_FromBaseTable()
                .where()
                .partition()
                 .Eq("test")
                .orderByCluster2Descending()
                .groupBy()
                .cluster1_cluster2()
                .getList();`

**Comment by doanduyhai** [comment]
It is not an issue. **By design** Cassandra only allow you to use `ORDER BY` on the **1st clustering column** in your query

**Comment by RaAleks** [comment]
Oh, thanks for quick response, just tried query to cassandra in console, and you are absolutely right! Many thanks!

**Comment by RaAleks** [comment]
But if i write this request, cassandra allow me to make second clustering column in desc order.
SELECT * FROM test WHERE category = 'test' ORDER BY cluster1 DESC, cluster2 DESC;

But achilles not allows.

**Comment by doanduyhai** [comment]
Which version of Cassandra are you using ?

**Comment by doanduyhai** [comment]
Also please provide CREATE TABLE script
