### ISSUE TITLE
Achilles can't deserialize undefined field into primitive

### ISSUE THREAD

**Issue by ook** [doanduyhai/Achilles#357]
Hi @doanduyhai ,

When you use Achilles to map a cassandra boolean into java primitive, Achilles will raise if the field is undefined.

I'd expect it map to default java primitive value (`false` for boolean, `0` for integer, etc.)
I tried to workaround using a Codec but as stated in #330 undefined cassandra value doesn't trigger the Codec.

**Comment by ook** [comment]
Yes, value never written into Cassandra (as you can do for non key or non clustering fields).

**Comment by doanduyhai** [comment]
So a very simple work-around:

1. do **not** use primitive types for **nullable** values in Cassandra, use rather object type `Boolean`
2. use `Optional<Boolean>` type in **Achilles**

**Comment by ook** [comment]
Thank you for your answer. I guess that could make its way into a FAQ.
