### ISSUE TITLE
Jackson version is not updated in Maven repo

### ISSUE THREAD

**Issue by vrudikov** [doanduyhai/Achilles#362]
Hi, @doanduyhai 

Glad to see you again
So I saw that you updated Jackson version on Mar 31 and released `6.0.2`
https://github.com/doanduyhai/Achilles/commit/8a2d0cc5721f753ea134a624c16b5b4dc09def4b#diff-0a369498a5a8db3ac8fa606b544c9810

But when I checked Maven repo - Jackson `2.3.3` version is still there
https://mvnrepository.com/artifact/info.archinnov/achilles-core/6.0.2

<img width="927" alt="image" src="https://user-images.githubusercontent.com/493714/59103180-cf429f80-8936-11e9-8d92-05fda8a77c39.png">

Is it some error?

**Comment by doanduyhai** [comment]
Weird, when using `mvn dependency:tree | grep jackson` on the master, here is what I can see:

```>(master|)
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.9.8:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.8:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.8:compile
[INFO] +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.8:compile
[INFO] |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.2:compile
[INFO] |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.2:compile
```

It looks like there is a bug with mvnrepository website. Can you confirm on your side that you get Jackson v 2.9.8 with the above command ?

**Comment by vrudikov** [comment]
No. I see 2.3.3

**Comment by vrudikov** [comment]
Here is my proof
<img width="555" alt="image" src="https://user-images.githubusercontent.com/493714/59115558-3caff980-8952-11e9-9f7c-a2918ac519c3.png">

**Comment by doanduyhai** [comment]
Ok I get it, it's pretty clear.

The version of **Achilles** with 2.9.8 of Jackson is 6.0.3-SNAPSHOT, which is not released yet

![image](https://user-images.githubusercontent.com/1532977/59119968-7da90d80-8954-11e9-91d2-61e1d9f61f7f.png)

So there is nothing wrong indeed

**Comment by vrudikov** [comment]
Ok. When we can expect it to be released?

**Comment by doanduyhai** [comment]
I'll attempt a release this weekend

**Comment by vrudikov** [comment]
Awesome. Thank you

**Comment by doanduyhai** [comment]
6.0.3 released

**Comment by vrudikov** [comment]
Thank you! Update of the year for us 👍

**Comment by vrudikov** [comment]
Weird. https://mvnrepository.com/artifact/info.archinnov/achilles-core/6.0.3
`[404] Not Found: /artifact/info.archinnov/achilles-core/6.0.3`
Is release is a something that should take several days? Or maybe Maven Repo issues?

**Comment by doanduyhai** [comment]
It takes some hours to be uploaded into Maven Central

![image](https://user-images.githubusercontent.com/1532977/59145314-57ca4a00-89e2-11e9-8617-a1ef1d28e8c2.png)
