### ISSUE TITLE
Multiple AbstractCQLCompatibleType & FunctionCall for token function

### ISSUE THREAD

**Issue by RaAleks** [doanduyhai/Achilles#363]
Hi @doanduyhai  Could you please add multiple AbstractCQLCompatibleType & FunctionCall for token function?

If i have table with more than one Parttiotion key, query should be as this for example:

**SELECT token(id1,id2) AS table_token FROM keyspace.example_table WHERE token(id1,id2)>-token_value**;

No in Achilles i can implement only this way: 

**SELECT token(id1) AS table_token FROM keyspace.example_table WHERE token(id1,id2)>-token_value;**

So, request above throws NPE because i should provide two token keys.

**achilles look like this:**
   manager
                .dsl()
                .select()
                .function(SystemFunctions.token(Table_AchillesMeta.COLUMNS.PARTTITION_ONE), "tokens")
                .fromBaseTable()
                .where()
                .tokenValueOf_id1_id2()
                .Gt(some_long_value)
                .getTypedMaps();

**This what i want to ask you:** 

manager
                .dsl()
                .select()
                .function(SystemFunctions
                                           .token(Table_AchillesMeta.COLUMNS.PARTTITION_ONE,
                                                      Table_AchillesMeta.COLUMNS.PARTTITION_TWO),
                                           "tokens")
                .fromBaseTable()
                .where()
                .tokenValueOf_id1_id2()
                .Gt(some_long_value)
                .getTypedMaps()

**Comment by doanduyhai** [comment]
Humm, thanks for the remark, I'm going to check the source code to see how difficult it is to implement this function

**Comment by RaAleks** [comment]
Many thanks for quick response!

**Comment by vrudikov** [comment]
+1

**Comment by doanduyhai** [comment]
1) I have left the current impl of `token()` function to avoid breaking change and for backward compatibility

2) I have added a new type-safe `token()`  function which only accept the type `PartitionKeys_Type`. This generated type has been introduced for the purpose

The usage is

```java
TypedMap typedMap = manager
    .dsl()
    .select()
    .function(SystemFunctions.token(MyEntity_AchillesMeta.COLUMNS.PARTITION_KEYS), "tokens")
    .fromBaseTable()
    ....

```

Please use the `xxx_AchillesMeta.COLUMNS.PARTITION_KEYS` that has been introduced for this purpose. If your table has a composite partition key, the **generated field**  `PARTITION_KEYS`  will reference all of them

**Comment by vrudikov** [comment]
Awesome. Thank you!

**Comment by RaAleks** [comment]
Thank you!

**Comment by RaAleks** [comment]
@doanduyhai When you expect to release this changes?

**Comment by doanduyhai** [comment]
I can attempt a minor release tonight. Expect it to be available on Maven Central in 24h max

**Comment by doanduyhai** [comment]
Just released. Will be available in a few hours on Maven Central (Achilles 6.0.4)

**Comment by RaAleks** [comment]
Once again, thank you!

**Comment by RaAleks** [comment]
@doanduyhai I've been update achilles version, and now i have such error :
"Invalid argument for 'token' function, it does not accept function call as argument, only simple column"

I think that it is due to Override method isFunctionCall always return true and PartitionKeys_Type implements FunctionCall.

**Comment by doanduyhai** [comment]
Let me check with a sample project

**Comment by doanduyhai** [comment]
So I just tested:

```java

@Table(keyspace = KEYSPACE, table = "composite_partitions")
@Immutable
public class CompositePartitionKeyEntity {

    @PartitionKey(1)
    public final Long id;

    @PartitionKey(2)
    public final UUID uuid;

    @Column
    public final String value;


    public CompositePartitionKeyEntity(Long id, UUID uuid, String value) {
        this.id = id;
        this.uuid = uuid;
        this.value = value;
    }
}

```

```java

    @Rule
    public AchillesTestResource<ManagerFactory> resource = AchillesTestResourceBuilder
            .forJunit()
            .createAndUseKeyspace(KEYSPACE)
            .entityClassesToTruncate(CompositePartitionKeyEntity.class)
            .truncateBeforeAndAfterTest()
            .build((cluster, statementsCache) -> ManagerFactoryBuilder
                    .builder(cluster)
                    .withStatementsCache(statementsCache)
                    .doForceSchemaCreation(true)
                    .withDefaultKeyspaceName(KEYSPACE)
                    .build());

    @Test
    public void should_test() throws Exception {
        //Given
        CompositePartitionKeyEntity_Manager manager = resource.getManagerFactory().forCompositePartitionKeyEntity();
        Long id = RandomUtils.nextLong(0L, Long.MAX_VALUE);
        UUID uuid = UUID.randomUUID();
        String value = RandomStringUtils.randomAlphabetic(10);

        CompositePartitionKeyEntity entity = new CompositePartitionKeyEntity(id, uuid, value);

        manager.crud().insert(entity).execute();

        //When
        TypedMap typedMap = manager
                .dsl()
                .select()
                .value()
                .function(SystemFunctions.token(CompositePartitionKeyEntity_AchillesMeta.COLUMNS.PARTITION_KEYS), "tokens")
                .fromBaseTable()
                .where()
                .id().Eq(id)
                .uuid().Eq(uuid)
                .getTypedMap();


        //Then
        assertThat(typedMap).isNotNull();
        assertThat(typedMap).isNotEmpty();
        assertThat(typedMap.<Long>getTyped("tokens")).isNotNull();
    }

```

Everything compiles correctly and the test is green

You should probably do a clean compile (`mvn clean compile`) to remove any left-overs of previously generated code

**Comment by RaAleks** [comment]
@doanduyhai Can you pls try such request 

manager
                .dsl()
                .select()
                .value()
                .function(SystemFunctions.token(Order_AchillesMeta.COLUMNS.), "tokens")
                .fromBaseTable()
                .where()
                .tokenValueOf_id_uuid()
                .Gt(Long.MIN_VALUE)
                .limit(10)
                .getTypedMaps();

**Comment by vrudikov** [comment]
@doanduyhai can you push your test - so we can test everything and create a PR with extended test, plz

**Comment by doanduyhai** [comment]
There is a mistake, if should NOT be `.function(SystemFunctions.token(CompositePartitionKeyEntity_AchillesMeta.COLUMNS), "tokens")` but `.function(SystemFunctions.token(CompositePartitionKeyEntity_AchillesMeta.COLUMNS.PARTITION_KEYS), "tokens")`

I've pushed a branch `TokenFunction` on the sample test projet **[KillrChat](https://github.com/doanduyhai/killrchat/tree/TokenFunction)**. You can checkout the project and execute the integration test `NewTest`

**Comment by RaAleks** [comment]
Oh, sorry it seems to my i fixed my comment. I've tried such query 
Ok, ill check out project and try to reproduce. Thanks!

**Comment by RaAleks** [comment]
Just tested, and it is ok! Will check what the problem in my project! Thanks.
