### ISSUE TITLE
Configurable protocol version

### ISSUE THREAD

**Issue by hjizettle** [doanduyhai/Achilles#374]
Currently the internal code creating the sessions used in the embedded cassandra instance looks like this:

```java
Cluster cluster = Cluster.builder()
                .addContactPoint(host)
                .withPort(cqlPort)
                .withClusterName(clusterName)
                .withCompression(compression)
                .withLoadBalancingPolicy(loadBalancingPolicy)
                .withRetryPolicy(retryPolicy)
                .withReconnectionPolicy(reconnectionPolicy)
                .withProtocolVersion(ProtocolVersion.NEWEST_SUPPORTED)
                .withSocketOptions(socketOptions)
                .withoutJMXReporting()
                .build();
```

This breaks us when upgrading to driver 3.11.0 since the newest supported version is changed to V5.
I think it was a harsh move in a minor version bump but it is what it is.

Would it be possible to expose this property via the `CassandraEmbeddedServerBuilder`?

**Comment by hjizettle** [comment]
I created a tiny patch for this but it would be great if it could be backported to previously still released versions @doanduyhai

**Comment by doanduyhai** [comment]
Thank you @hjizettle for the patch

I'll do a release this week-end to include your patch 

Regards
