### ISSUE TITLE
Add support for custom type

### ISSUE THREAD

**Issue by doanduyhai** [doanduyhai/Achilles#47]

**Comment by gkgupta** [comment]
Is the support for UDT added to Achilles? As I wasn't able to find it anywhere in the documentation. Right now we are forced to use @Json to store custom types.

**Comment by ranjansatya** [comment]
When UDT support is coming in Achilles ?

**Comment by doanduyhai** [comment]
It will be supported in Achilles 4, I'm working on version 4 right now

**Comment by vishvesh** [comment]
Hi @doanduyhai , any update on UDT?

**Comment by amorillotraxens** [comment]
Hi @doanduyhai, do you have any plan to support this feature ?

**Comment by doanduyhai** [comment]
Will be supported in Achilles 4.

Achilles 4 status is Work In Progress, do not expect any release before September/October since it's a major rewrite of the framework.

In the meantime, you can use `TypedQuery`  or  `NativeQuery` if working with UDT

**Comment by amorillotraxens** [comment]
Hi @doanduyhai, do you have any update on this feature ?

**Comment by doanduyhai** [comment]
Achilles 4 will support UDT out of the box. The development is 95% done, I
just need to document the code, update the general documents, add some
integration tests. Due to the Cassandra Summit this week the development
has been slowed down but expect a first release beginning of October
Le 23 sept. 2015 09:46, "amorillotraxens" <notifications@github.com> a
écrit :

**Comment by amorillotraxens** [comment]
Hi @doanduyhai, do you have any release date for Achilles 4 ?

**Comment by doanduyhai** [comment]
I'm writing the documentation right now. The dev is finished. Sorry for the
delay. The release should be done in a few days

**Comment by doanduyhai** [comment]
Fixed in Achilles 4.0.0
